// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Load environment variables
// Priority: .env.local (local dev) -> .env (production/AWS)
dotenv.config({ path: ".env.local" });
dotenv.config({ path: ".env" });

export default defineConfig({
  schema: "packages/db/prisma/schema.prisma",
  migrations: {
    path: "packages/db/prisma/migrations",
  },
  datasource: {
    // Prisma CLI operations need a direct connection when DATABASE_URL points
    // at a transaction pooler (for example Supabase/PgBouncer).
    url: process.env["DIRECT_URL"]
      || process.env["POSTGRES_URL_NON_POOLING"]
      || process.env["DATABASE_URL"]
      || process.env["POSTGRES_PRISMA_URL"],
  },
});
