export const MAX_ILLUSTRATION_FILE_BYTES = 4 * 1024 * 1024;

const MAX_MULTIPART_OVERHEAD_BYTES = 128 * 1024;
export const MAX_ILLUSTRATION_REQUEST_BYTES =
  MAX_ILLUSTRATION_FILE_BYTES + MAX_MULTIPART_OVERHEAD_BYTES;

export const ILLUSTRATION_FILE_SIZE_LABEL = '4MB';
